name: Build and Publish ra-apisix-oidc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Build
        run: make build-ra-apisix-oidc
        env:
          ARTE_NPMJS_TOKEN: ${{ secrets.ARTE_NPMJS_TOKEN }}
      - name: Publish to npm
        run: make publish
        env:
          ARTE_NPMJS_TOKEN: ${{ secrets.ARTE_NPMJS_TOKEN }}
